# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "dark" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: "Sohyeon Lee"

### Header
header:
  logo:
    image: "assets/img/logo2.png"
    alt: "Sohyeon Lee"

### Social
social:
  - title: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/sohyeon-lee-982a90313/"

  - title: "Github"
    icon: "fab fa-github"  # Github에 맞는 아이콘으로 변경
    url: "https://github.com/leesohyeon96"  # Github 프로필 URL로 변경

  - title: "Mail"
    icon: "fas fa-envelope"  # 메일을 나타내는 아이콘으로 변경
    url: "mailto:vkfkswjs26@gmail.com"  # 실제 메일 주소로 변

### Footer
footer:
  developer: "Developed by <strong>sohyeon</strong>"
  copyright: "<strong>SHL</strong>. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "진행중인 프로젝트"
      slug: "on-going-projects"
#      slug: "ui-ux-design" # on-going-projects

    - name: "완료된 프로젝트"
      slug: "completed-projects"
#      slug: "photography" # completed-projects

#    - name: "Development"
#      slug: "development"

#    - name: "Branding"
#      slug: "branding"
